FROM node:14 AS build
ENV NODE_ENV production
WORKDIR /app
ADD package.json package-lock.json /app/
RUN npm ci --dev
ADD . /app/
RUN npx tsc

FROM node:14
ARG PORT
ENV PORT $PORT
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN $GITHUB_TOKEN
ARG GITHUB_ORGANIZATION
ENV GITHUB_ORGANIZATION $GITHUB_ORGANIZATION
ARG GITHUB_REPOSITORY
ENV GITHUB_REPOSITORY $GITHUB_REPOSITORY
ARG JIRA_HOST
ENV JIRA_HOST $JIRA_HOST 
ARG JIRA_ISSUER_EMAIL
ENV JIRA_ISSUER_EMAIL $JIRA_ISSUER_EMAIL
ARG JIRA_PROJECT
ENV JIRA_PROJECT $JIRA_PROJECT 
ARG JIRA_PROJECT_ID
ENV JIRA_PROJECT_ID$JIRA_PROJECT_ID
ARG JIRA_API_TOKEN
ENV JIRA_API_TOKEN $JIRA_API_TOKEN
ARG JIRA_DONE_TRANSITION_ID
ENV JIRA_DONE_TRANSITION_ID $JIRA_DONE_TRANSITION_ID
WORKDIR /app
ADD package.json package-lock.json /app/
RUN echo $'NODE_ENV=production\nENVIRONMENT='$ENVIRONMENT'PORT='$PORT'\nGITHUB_TOKEN='$GITHUB_TOKEN'\nGITHUB_ORGANIZATION='$GITHUB_ORGANIZATION'\nGITHUB_REPOSITORY='$GITHUB_REPOSITORY'\nJIRA_HOST='$JIRA_HOST'\nJIRA_ISSUER_EMAIL='$JIRA_ISSUER_EMAIL'\nJIRA_PROJECT='$JIRA_PROJECT'\nJIRA_PROJECT_ID='$JIRA_PROJECT_ID'\nJIRA_API_TOKEN='$JIRA_API_TOKEN'\nJIRA_DONE_TRANSITION_ID='$JIRA_DONE_TRANSITION_ID >> .env && npm ci --prod
COPY --from=build /app/build/ /app/